spring:
  application:
    name: Greeting
  cloud:
    zookeeper:
      connect-string: localhost:2181

  main:
    allow-bean-definition-overriding: true
server:
  port: 8083
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
